<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Voting\Doctrine;

use MSBios\Voting\Resource\Record\PollInterface;

/** @var int $identifier */
$identifier = 'SOME_RELATION';

/** @var string $relation */
$relation = 'SOME_RELATION[100550]';

/** @var PollInterface $poll */
$poll = $this->poll()->find($identifier, $relation);

?>

<?php /** @var \Zend\View\Helper\FlashMessenger $flash */ ?>
<?php $flash = $this->flashMessenger(); ?>

<?php if ($flash->hasSuccessMessages()) : ?>

    <div class="alert alert-success no-border">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <span class="text-semibold"><?= $this->translate('Success!'); ?></span>
        <?= implode(', ', $flash->getSuccessMessages()); ?>
    </div>

<?php elseif ($flash->hasInfoMessages()) : ?>

    <div class="alert alert-info no-border">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <span class="text-semibold"><?= $this->translate('Success!'); ?></span>
        <?= implode(', ', $flash->getInfoMessages()); ?>
    </div>

<?php endif; ?>

<?php if ($flash->hasWarningMessages()) : ?>

    <div class="alert alert-danger no-border">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <span class="text-semibold"><?= $this->translate('Warning!'); ?></span>
        <?= implode(', ', $flash->getWarningMessages()); ?>
    </div>

<?php endif; ?>

<?php if ($poll): ?>
    <h1>
        <?= $poll->getSubject(); ?><br>
        <small class="text-muted">
            <b>Total Votes:</b>
            <small><?= $poll->getTotal(); ?></small>
            <b>Avg:</b>
            <small><?= number_format($poll->getAvg(), 2); ?></small>
        </small>
    </h1>

    <?php

    /** @var \Zend\Form\FormInterface $form */
    $form = $this->form;
    $form->setData([
        'poll_relation' => $poll->getCode(),
        'poll_identifier' => $poll->getPoll()->getId()
    ]);
    $form->setAttribute('action', $this->url('home/voting'));
    $form->prepare();

    ?>

    <div style="margin-bottom: 20px;">
        <?php if (!$this->poll()->check($poll)) : ?>
            <?= $this->form()->openTag($form); ?>
            <ul>
                <?php $element = $form->get('poll_option_identifier'); ?>

                <?php foreach ($this->poll()->variants($poll) as $variant): ?>
                    <li>
                        <label>
                            <?= $this->formRadio(new \Zend\Form\Element\Radio($element->getName(), [
                                'value_options' => [[
                                    'value' => $variant['id'],
                                ]]
                            ])); ?>
                            <?= $variant['name']; ?>
                        </label>
                        <small>
                            Total: <?= $variant['total']; ?>
                            Percents: <?= number_format($variant['percent'], 2); ?>%
                            <?php if ($variant['total']): ?>
                                <a href="<?= $this->url('home/voting-cancel', [
                                    'poll_identifier' => $poll->getPoll()->getId(),
                                    'poll_option_identifier' => $variant['id'],
                                    'poll_relation' => $poll->getCode()
                                ]); ?>">Undo</a>
                            <?php endif; ?>
                        </small>

                    </li>
                <?php endforeach; ?>
            </ul>
            <?= $this->formElement($form->get('poll_relation')); ?>
            <?= $this->formElement($form->get('poll_redirect')); ?>
            <?= $this->formButton($form->get('poll_identifier')->setAttribute('class', 'btn btn-default')->setLabel('Button')); ?>
            <?= $this->form()->closeTag($form); ?>
        <?php else: ?>
            <?php $votes = $this->poll()->votes($poll); ?>

            <ul>
                <?php foreach ($votes as $variant): ?>
                    <li>
                        <?= $variant['name']; ?>
                        <small><?= $variant['vote']; ?></small>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
<?php else: ?>
    <h1>Empty Poll</h1>
<?php endif; ?>

<ul>
    <li>Vote Module version: <?= \MSBios\Voting\Doctrine\Module::VERSION; ?></li>
    <li>Vote Resource Module version: <?= \MSBios\Voting\Resource\Doctrine\Module::VERSION; ?></li>
</ul>