<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Voting\Doctrine\Controller;

use Zend\Mvc\Controller\AbstractActionController;

/**
 * Class IndexController
 * @package MSBios\Voting\Doctrine\Controller
 */
class IndexController extends AbstractActionController
{
    public function indexAction()
    {
        if ($this->getRequest()->isPost()) {
            if ($this->poll()->setData($this->params()->fromPost())->vote()) {
                $this->flashMessenger()->addSuccessMessage('Your voice has been accepted and processed.');
                return $this->redirect()->toRoute('home');
            }
        }

        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
}
