<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Voting\Doctrine\Controller;

use MSBios\Voting\Controller\IndexController as DefaultIndexController;

/**
 * Class IndexController
 * @package MSBios\Voting\Doctrine\Controller
 */
class IndexController extends DefaultIndexController
{
    public function indexAction()
    {

        if ($this->getRequest()->isPost()) {
            $this->poll()->setValue($this->params()->fromPost());
        }

        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
}
