<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Voting\Doctrine\Form;

use DoctrineModule\Form\Element\ObjectRadio;
use DoctrineModule\Persistence\ObjectManagerAwareInterface;
use MSBios\Doctrine\ObjectManagerAwareTrait;
use MSBios\Voting\Form\PollForm as DefaultPollForm;
use MSBios\Voting\Resource\Doctrine\Entity\Option;

/**
 * Class PollForm
 * @package MSBios\Voting\Doctrine\Form
 */
class PollForm extends DefaultPollForm implements ObjectManagerAwareInterface
{
    use ObjectManagerAwareTrait;

    /**
     * @param array|\ArrayAccess|\Traversable $data
     * @return \Zend\Form\Form
     */
    public function setData($data)
    {
        $this->add([
            'type' => ObjectRadio::class,
            'name' => 'poll_option_identifier',
            'options' => [
                'object_manager' => $this->getObjectManager(),
                'target_class' => Option::class,
                'property' => 'name',
                'is_method' => true,
                'find_method' => [
                    'name' => 'findBy',
                    'params' => [
                        'criteria' => [
                            'poll' => $data['poll_identifier']
                        ],
                        // I need this to be the content id
                        'orderBy' => ['priority' => 'DESC'],
                    ],
                ]
            ]
        ]);

        return parent::setData($data); // TODO: Change the autogenerated stub
    }
}
